export const capabilities = [
  {
    category: 'Natural Language Processing',
    icon: '💬',
    description: 'Advanced text understanding, generation, and analysis',
    items: [
      {
        name: 'Text Summarization',
        description: 'Condense long documents into concise, accurate summaries while preserving key information.',
        inputs: ['Long-form documents', 'Reports', 'Articles', 'Meeting transcripts'],
        outputs: ['Executive summaries', 'Key points lists', 'Abstract generation'],
        constraints: 'Best results with well-structured text; very long documents may need chunking.',
        tags: ['NLP', 'Summarization', 'Content'],
      },
      {
        name: 'Sentiment Analysis',
        description: 'Detect emotional tone, sentiment, and opinion in text across multiple languages.',
        inputs: ['Customer reviews', 'Social media posts', 'Survey responses', 'Support tickets'],
        outputs: ['Sentiment scores', 'Emotion classification', 'Opinion mining results'],
        constraints: 'Context-dependent; sarcasm and nuance may require additional processing.',
        tags: ['NLP', 'Sentiment', 'Analysis'],
      },
      {
        name: 'Named Entity Recognition',
        description: 'Identify and classify entities like people, organizations, locations, dates, and more.',
        inputs: ['Unstructured text', 'Documents', 'News articles', 'Legal contracts'],
        outputs: ['Tagged entities', 'Entity relationships', 'Structured data extraction'],
        constraints: 'Accuracy varies by domain; custom training may improve specialized entity recognition.',
        tags: ['NLP', 'Extraction', 'Entities'],
      },
      {
        name: 'Language Translation',
        description: 'Translate text between multiple languages while maintaining context and meaning.',
        inputs: ['Text in source language', 'Documents', 'Web content'],
        outputs: ['Translated text', 'Multilingual content', 'Localized materials'],
        constraints: 'Quality varies by language pair; idiomatic expressions may need review.',
        tags: ['NLP', 'Translation', 'Multilingual'],
      },
    ],
  },
  {
    category: 'Document Intelligence',
    icon: '📄',
    description: 'Extract insights and structure from documents',
    items: [
      {
        name: 'Document Classification',
        description: 'Automatically categorize documents by type, topic, or custom taxonomies.',
        inputs: ['PDFs', 'Word documents', 'Scanned images', 'Text files'],
        outputs: ['Document categories', 'Confidence scores', 'Metadata tags'],
        constraints: 'Requires clear document structure; OCR quality affects scanned document accuracy.',
        tags: ['Documents', 'Classification', 'Organization'],
      },
      {
        name: 'Information Extraction',
        description: 'Pull specific data points, fields, and structured information from documents.',
        inputs: ['Forms', 'Invoices', 'Contracts', 'Receipts', 'Reports'],
        outputs: ['Structured data', 'Key-value pairs', 'Database-ready records'],
        constraints: 'Template-based documents work best; highly variable formats may need customization.',
        tags: ['Documents', 'Extraction', 'Data'],
      },
      {
        name: 'Question Answering',
        description: 'Answer questions based on document content with source citations.',
        inputs: ['Documents', 'Knowledge bases', 'Manuals', 'FAQs'],
        outputs: ['Direct answers', 'Source citations', 'Confidence indicators'],
        constraints: 'Answer quality depends on document clarity; ambiguous questions may need refinement.',
        tags: ['Documents', 'Q&A', 'Search'],
      },
    ],
  },
  {
    category: 'Content Generation',
    icon: '✍️',
    description: 'Create professional content across formats',
    items: [
      {
        name: 'Text Generation',
        description: 'Generate coherent, contextually appropriate text for various business needs.',
        inputs: ['Prompts', 'Templates', 'Style guidelines', 'Topic descriptions'],
        outputs: ['Articles', 'Reports', 'Emails', 'Marketing copy', 'Documentation'],
        constraints: 'Generated content should be reviewed; factual accuracy requires verification.',
        tags: ['Generation', 'Content', 'Writing'],
      },
      {
        name: 'Template Completion',
        description: 'Fill in templates and forms with appropriate content based on context.',
        inputs: ['Templates', 'Partial data', 'Context information'],
        outputs: ['Completed documents', 'Filled forms', 'Standardized reports'],
        constraints: 'Works best with well-defined templates; complex logic may need custom rules.',
        tags: ['Generation', 'Templates', 'Automation'],
      },
      {
        name: 'Content Rewriting',
        description: 'Rephrase, simplify, or adapt content for different audiences and purposes.',
        inputs: ['Original text', 'Target audience', 'Tone requirements'],
        outputs: ['Rewritten content', 'Simplified versions', 'Adapted materials'],
        constraints: 'Preserves meaning but may alter nuance; review recommended for critical content.',
        tags: ['Generation', 'Rewriting', 'Adaptation'],
      },
    ],
  },
  {
    category: 'Data Analysis',
    icon: '📊',
    description: 'Analyze patterns and extract insights from data',
    items: [
      {
        name: 'Text Analytics',
        description: 'Discover patterns, trends, and insights in large text collections.',
        inputs: ['Text corpora', 'Customer feedback', 'Survey responses', 'Social media data'],
        outputs: ['Trend reports', 'Topic clusters', 'Insight summaries', 'Visualizations'],
        constraints: 'Requires sufficient data volume; interpretation may need domain expertise.',
        tags: ['Analysis', 'Insights', 'Trends'],
      },
      {
        name: 'Comparative Analysis',
        description: 'Compare documents, datasets, or text segments to identify differences and similarities.',
        inputs: ['Multiple documents', 'Versions', 'Datasets', 'Text segments'],
        outputs: ['Comparison reports', 'Difference highlights', 'Similarity scores'],
        constraints: 'Most effective with comparable formats; large-scale comparisons may need batching.',
        tags: ['Analysis', 'Comparison', 'Review'],
      },
    ],
  },
  {
    category: 'Workflow Automation',
    icon: '⚙️',
    description: 'Automate repetitive tasks and processes',
    items: [
      {
        name: 'Document Routing',
        description: 'Automatically classify and route documents to appropriate teams or workflows.',
        inputs: ['Incoming documents', 'Routing rules', 'Team assignments'],
        outputs: ['Routed documents', 'Assignment notifications', 'Workflow triggers'],
        constraints: 'Requires defined routing logic; edge cases may need manual review.',
        tags: ['Automation', 'Workflow', 'Routing'],
      },
      {
        name: 'Data Validation',
        description: 'Check data quality, completeness, and consistency automatically.',
        inputs: ['Data records', 'Validation rules', 'Quality criteria'],
        outputs: ['Validation reports', 'Error flags', 'Quality scores'],
        constraints: 'Rules must be clearly defined; complex validation may need custom logic.',
        tags: ['Automation', 'Validation', 'Quality'],
      },
    ],
  },
];
